version: "3.8"

services:
  fastapi-server:
    build: ./server
    container_name: fastapi-server
    ports:
      - "8000:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      jaeger:
        condition: service_started
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq/
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318/v1/traces

  clickscollector:
    build: ./microservices/ClicksCollector
    container_name: clickscollector
    depends_on:
      rabbitmq:
        condition: service_healthy
      jaeger:
        condition: service_started
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq/
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318/v1/traces


  rawdatacollector:
    build: ./microservices/RawDataCollector
    container_name: rawdatacollector
    volumes:
      - ./microservices/RawDataCollector:/app:rw
    ports:
      - "5678:5678"
    command: >
      python -u app/main.py
    env_file:
      - ./microservices/RawDataCollector/.env
    environment:
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USER=${NEO4J_USERNAME}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - NEO4J_DATABASE=${NEO4J_DATABASE}
      - AMQP_URL=amqp://guest:guest@rabbitmq/
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318/v1/traces
    depends_on:
      rabbitmq:
        condition: service_healthy
      jaeger:
        condition: service_started
    stdin_open: true
    tty: true

  recomendationsreader:
    build: ./microservices/RecomendationsReader
    container_name: recomendationsreader
    depends_on:
      rabbitmq:
        condition: service_healthy
      jaeger:
        condition: service_started
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq/
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318/v1/traces

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "4318:4318"